version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    links:
     - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classic-trader
      MYSQL_USER: cltr
      MYSQL_PASSWORD: cltr
    volumes:
      - /var/lib/mysql
